export const data = 
{    
  columns: [
    {
      label: 'Position',
      field: 'position',
      width: 200,
    },
    {
      label: 'Company',
      field: 'company',
      width: 200,
      attributes: {
        'aria-controls': 'DataTable',
        'aria-label': 'Company',
    },
    },
    {
      label: 'Industry',
      field: 'industry',
      width: 200,
    },
    {
      label: 'Location',
      field: 'location',
      width: 200,
    },
    {
      label: 'Salary',
      field: 'salary',
      sort: 'asc',
      width: 100,
    },
    {
      label: 'Length',
      field: 'length',
      width: 100,
    },
    {
      label: 'Skills',
      field: 'skills',
      width: 300,
    },
    {
      label: 'Remote',
      field: 'remote',
      width: 100,
    },
    ],
    rows: [
      {
        position: 'Software Engineer Intern',
        company: 'Google',
        industry: 'Technology',
        location: 'Toronto, ON',
        salary: '67000',
        length: '12 month',
        skills: 'JavaScript, NodeJS, Python, Flask',
        remote: 'Remote'
      },
      {
        position: 'Technical Consulting Intern',
        company: 'TD Bank',
        industry: 'Consulting',
        location: 'Toronto, ON',
        salary: '60000',
        length: '12 month',
        skills: 'JavaScript, Python, Power Point',
        remote: 'Remote',
      }, 
      {
        position: 'Software Engineer Intern',
        company: 'TD Bank',
        industry: 'Technology',
        location: 'Ottawa, ON',
        salary: '66000',
        length: '12 month',
        skills: 'Python, Flask, Docker',
        remote: 'In-Office',
      }, 
      {
        position: 'Data Science Intern',
        company: 'RBC',
        industry: 'Finance',
        location: 'Vancouver, BC',
        salary: '59000',
        length: '8 month',
        skills: 'Python, R, NumPy',
        remote: 'In-Office',
      }, 
      {
        position: 'Software Engineer Intern',
        company: 'Shopify',
        industry: 'E-Commerce',
        location: 'Ottawa, ON',
        salary: '68000',
        length: '8 month',
        skills: 'Docker, Git, Kubernetes',
        remote: 'Remote',
      }, 
      {
        position: 'Data Science Intern',
        company: 'Shopify',
        industry: 'E-Commerce',
        location: 'Ottawa, ON',
        salary: '60000',
        length: '12 month',
        skills: 'Python, R, NumPy',
        remote: 'Remote',
      }, 
      {
        position: 'Financial Analyst Intern',
        company: 'RBC',
        industry: 'Finance',
        location: 'Toronto, ON',
        salary: '55000',
        length: '12 month',
        skills: 'Power Point, Excel, Python',
        remote: 'In-Office',
      }, 
      {
        position: 'Research Intern',
        company: 'Queens University',
        industry: 'Biology',
        location: 'Kingston, ON',
        salary: '50000',
        length: '12 month',
        skills: 'Power Point, Excel',
        remote: 'In-Office',
      }, 
      {
        position: 'Product Manager Intern',
        company: 'Microsoft',
        industry: 'Technology',
        location: 'Vancouver, ON',
        salary: '63000',
        length: '8 month',
        skills: 'Docker, Git, Kubernetes',
        remote: 'Remote',
      },
      {
        position: 'Product Manager Intern',
        company: 'Google',
        industry: 'Technology',
        location: 'Toronto, ON',
        salary: '70000',
        length: '8 month',
        skills: 'Jira, Excel, Flask, JavaScript',
        remote: 'Remote',
      },  
    ],
  }
